services:
    traefik:
        image: traefik:v3.0
        ports:
            - "80:80"
            - "443:443"
        command:
            - "--providers.docker=true"
            - "--entrypoints.web.address=:80"
            - "--api.insecure=true"  
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        networks:
            - prod
        deploy:
            mode: global  

    postgres:
        build:
            context: ./api_ecom
            dockerfile: Dockerfile.postgres
        restart: always
        volumes:
            - ../ecommerce_data:/data
        deploy:
            resources:
                limits:
                    memory: 2G
        networks:
            - prod

    api:
        build:
            context: ./api_ecom
            dockerfile: Dockerfile.django
        volumes:
            - ./api_ecom:/code
        env_file: .env
        deploy:
            replicas: 3
            resources:
                limits:
                    memory: 3G
        extra_hosts:
            - "localhost:host-gateway" # to be removed in production
        networks:
            - prod
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=PathPrefix(`/api/v1/`)"
            - "traefik.http.routers.api.entrypoints=web"
            - "traefik.http.services.api.loadbalancer.server.port=8000"

    website:
        build:
            context: ./web_ecom
            dockerfile: Dockerfile.django
        volumes:
            - ./web_ecom:/code
        env_file: .env
        deploy:
            replicas: 3
            resources:
                limits:
                    memory: 3G
        extra_hosts:
            - "localhost:host-gateway" # to be removed in production
        networks:
            - prod
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.website.rule=PathPrefix(`/`) && !PathPrefix(`/api/v1/`)"
            - "traefik.http.routers.website.entrypoints=web"
            - "traefik.http.services.website.loadbalancer.server.port=8000"

    redis:
        build:
            context: ./api_ecom
            dockerfile: Dockerfile.redis
        image: redis:7
        container_name: redis
        ports:
            - "6379:6379"
        restart: always
        volumes:
            - ../redis_data:/data
        networks:
            - prod

    beat:
        build:
            context: ./api_ecom
            dockerfile: Dockerfile.beat
        volumes:
            - ./api_ecom:/code
        env_file: .env
        networks:
            - prod

    worker:
        build:
            context: ./api_ecom
            dockerfile: Dockerfile.worker
        volumes:
            - ./api_ecom:/code
        env_file: .env
        restart: always
        networks:
            - prod

networks:
    prod:
        driver: bridge
